### ISSUE TITLE
what is the mixstyle class used for?

### ISSUE THREAD

**Issue by Espere-1119-Song** [mswzeus/GVRT#3]
During the training process and the evaluate process, I found that the mixstyle class was not called. So what is the mixstyle class used for?

**Comment by seonwoo-min** [comment]
@Espere-1119-Song, Thank you for your interest in our work.
MixStyle is one of the compared baseline algorithms. 
If you set "--algorithm" option as MixStyle, the _get_algoriithm_class function_ calls and uses the MiixStyle class.
https://github.com/mswzeus/GVRT/blob/6ecb2b8e069787933dda72bb61e33f956b586d6f/src/algorithms.py#L19-L23
You can also find the results for MixStyle in the experimental results table.

**Comment by Espere-1119-Song** [comment]
thanks a lot!
