### ISSUE TITLE
An error occurred when running the code to evaluate the model

### ISSUE THREAD

**Issue by ZhenyuLiu-SYSU** [mswzeus/GVRT#4]
Dear author:
I am glad to read this wonderful paper!
But when I run the _**evaluate_model.py**_, I had a error as follows.
![image](https://user-images.githubusercontent.com/74093654/227707312-a1fb7297-1ecb-4baf-be46-e6e547a6f31b.png)

I checked the code and found that when run this line in the _**evaluate_model.py**_, it had something wrong.
![image](https://user-images.githubusercontent.com/74093654/227707340-49b9263c-46d9-4acb-ac32-f903579c9015.png)

And I can't find any resolution to deal with this error.
Could you tell me how can I solve this problem?
I would appreciate it if you could reply as soon as possible!
Thank you again!

Best regards,
Zhenyu Liu

**Comment by seonwoo-min** [comment]
Hi @ZhenyuLiu-BJFU, 
Thank you for your interest in our work! 

It seems like the error comes from the coco-caption where java (>1.8.0) is required. (https://github.com/tylin/coco-caption)
Will you check whether your environment has the correct java installations?

**Comment by ZhenyuLiu-SYSU** [comment]
Thank you for your reply！
I think that's the reason,
I will try it and contact you if there are any questions.

Thank you again for your timely response！
