### ISSUE TITLE
A question about the new added code preprocess_texts.py

### ISSUE THREAD

**Issue by ZhenyuLiu-SYSU** [mswzeus/GVRT#6]
Dear author:
when I use the CUB_DG's descriptions.json to try to run the **preprocess_texts.py** to get the preprocess files, I found this error:
![image](https://user-images.githubusercontent.com/74093654/234021614-5ea60795-dd77-4c08-bdbd-2d125e2f0822.png)
And when I try my own json file, I also found that:
![image](https://user-images.githubusercontent.com/74093654/234022261-33086aae-0142-4eec-ab64-a99c3d0e2e5d.png)
I think the error is because  of the line**"texts_words = PTBTokenizer().tokenize(coco.imgToAnns)"**, because the texts_words can't be gotten.
Could you help me to see it?

**Comment by seonwoo-min** [comment]
I do not get any errors when I use the script and the CUB-DG dataset.
<code>texts_words</code> should be a dictionary object containing 11,788 key-value pairs. Each value is a list of 9 or 10 lists of tokenized words.
Please check if you have modified the <code>descriptions.json</code> file or if you are misusing any of the provided functions in your custom script.

In terms of using your own JSON file, you should also check whether the file correctly follows the COCO dataset format. You can look into the CUB-DG's description.json file or please refer to the following page (https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch).
