### ISSUE TITLE
 Inquiry about pretraining for Discriminator in sentence classification

### ISSUE THREAD

**Issue by JackeyWang777** [mswzeus/GVRT#7]
Hello,

First of all, thank you for the fantastic article!
I wanted to inquire about whether the Discriminator needs pretraining on sentence classification tasks. I noticed in the article "Generating visual explanations" from 2016, there was mention of pretraining. Could you please clarify whether pretraining for Discriminator is necessary, and if so, what approach would be recommended?
Thank you for your attention to this matter.

**Comment by seonwoo-min** [comment]
Hey, @JackeyWang777. Thanks for your interest in our work!
In our case, we do not pre-train the discriminator, a.k.a., sentence classifier. 
As you can check in our codes, all the additional modules (i.e., two classifiers, two projectors, an explainer, and a discriminator) are trained jointly from scratch without loading any pretrained weights.

Thanks,
Seonwoo

**Comment by JackeyWang777** [comment]
Thank you for your reply. I have another question, what are the meanings of these three files "texts_s.npy"( size [117819, 512])、 "texts_w.npy"(size #[117819, 64]) and "lengths.npy" in the dataset, and how to create these files for customized  dataests. Would it be convenient for you to share the code?

**Comment by JackeyWang777** [comment]
> Hey, @JackeyWang777. Thanks for your interest in our work! In our case, we do not pre-train the discriminator, a.k.a., sentence classifier. As you can check in our codes, all the additional modules (i.e., two classifiers, two projectors, an explainer, and a discriminator) are trained jointly from scratch without loading any pretrained weights.
> 
> Thanks, Seonwoo

정말 감사합니다
